# Generated by Django 6.0.4 on 2026-04-27 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('rightsholder', 'Rightsholder Agreement'), ('buyer', 'Buyer Terms of Service')], max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Signature'), ('signed', 'Signed'), ('expired', 'Expired'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signwell_document_id', models.CharField(max_length=255, unique=True)),
                ('embedded_signing_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_storage_key', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contract_type', 'version')},
            },
        ),
    ]
