# Generated by Django 6.0.4 on 2026-04-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('audience_size', models.CharField(max_length=10)),
                ('sports_audience_fit', models.FloatField()),
                ('track_virality', models.FloatField()),
                ('audio_file', models.FileField(upload_to='songs/audio/')),
            ],
        ),
    ]
