# Generated by Django 6.0.4 on 2026-04-28 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='song',
            name='isrc',
            field=models.CharField(default='PLACEHOLDER', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid ISRC (e.g. USRC17607839)', regex='^[A-Z]{2}[A-Z0-9]{3}\\d{7}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
