# Generated by Django 6.0.4 on 2026-04-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_is_approved_song_isrc_song_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
