# Generated by Django 6.0.4 on 2026-04-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='price',
            new_name='fixed_price',
        ),
        migrations.AddField(
            model_name='song',
            name='track_tier',
            field=models.CharField(choices=[('bid2clear', 'Bid2Clear'), ('preclear', 'PreClear'), ('artist_promo', 'Artist Promo')], default='preclear', max_length=20),
        ),
    ]
