# Generated by Django 6.0.4 on 2026-04-30 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0004_rename_price_song_fixed_price_song_track_tier'),
        ('users', '0002_artistprofile_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('bid2clear', 'Bid2Clear'), ('preclear', 'Preclear'), ('artist_promo', 'Artistpromo')], max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('usage_details', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientprofile')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='songs.song')),
            ],
        ),
    ]
