# Generated by Django 6.0.4 on 2026-04-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('bid2clear', 'Bid2Clear'), ('preclear', 'PreClear'), ('artist_promo', 'Artist Promo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='license',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
