# Generated by Django 6.0.4 on 2026-04-28 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0003_alter_song_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_song_title', models.CharField(blank=True, max_length=200, null=True)),
                ('external_artist_name', models.CharField(blank=True, max_length=200, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('unable_to_clear', 'Unable to Clear')], default='submitted', max_length=20)),
                ('usage_details', models.TextField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_requests', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_requests', to='songs.song')),
            ],
        ),
    ]
